version: '3'
services:
    tomcat:
        build:
            context: tomcat/
        ports:
            - "8080:8080"
    mysql:
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_HOST: "%"
        image: "mysql:5.7.20"
        ports:
            - "3306:3306"
    mlserver:
        build:
            context: csselectmlserver/
